name: my_event_planner
description: A simple My Event Planner Flutter app for UTS assignment
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  image_picker: ^1.0.5
  uuid: ^3.0.7
  
flutter:
  uses-material-design: true
